### PR TITLE
Select Spreadsheet translation

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep 👍

**Comment by donnapep** [comment]
@stulees Actually, I moved this into a new file - `google-drive-picker.json` - to better align with how we store translations for components. Do you agree? Thx.

**Comment by stulees** [comment]
@donnapep I like it, decouples it from just being used by spreadsheet. 👍

**Pull request merged**
