### PR TITLE
Add translations for Editor basic syntax validation

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps please review

### CODE REVIEW

**Comment by ezequielc** [comment]
@fjvallarino I think the description of the message is a bit too technical (Presentation Data Object). What do you think of "The content of you Presentation could not be parsed. Please check the syntax in HTML mode." ? Thanks

**Comment by fjvallarino** [comment]
@ezequielc I used that description (Presentation Data Object) mainly because the template itself uses it, so I assumed a user modifying that part of the code would be aware of that name. I have no trouble changing it, of course

**Comment by ezequielc** [comment]
@fjvallarino Makes sense, but I wasn't fully aware of Presentation Data Object meaning. I think my suggestion is a bit more descriptive. Thanks

**Comment by fjvallarino** [comment]
@ezequielc updated

**Comment by ezequielc** [comment]
@fjvallarino 👍 Thanks

**Pull request merged**
