### PR TITLE
Added transition texts for rss-widget

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep @stulees please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi I think some of these translations are pertaining to the scroll setting component for which there are translations already, so you may want to change this PR. I would look to the scroll setting component in widget-settings-ui-components to get familiar and also https://github.com/Rise-Vision/common-i18n/blob/master/src/locales_json/en/scroll.json for what translations already exist. Thanks

**Comment by rodrigopavezi** [comment]
@stulees I see, but I think they are really different. I think it is better separating them other them trying to tight them up. I would say otherwise if we would have to use the scroll component but I don't think that is the case, right? Thoughts?

**Comment by stulees** [comment]
@rodrigopavezi Okay good point. It's uncertain right now if we will be using scroll component so a separation for now seems good. You'll need to do a version bump first though, cheers.

**Comment by rodrigopavezi** [comment]
@stulees sorry, version bumped. cheers

**Comment by stulees** [comment]
@rodrigopavezi :+1:

**Pull request merged**
