### PR TITLE
Legacy presentation items warning message

### PR DESCRIPTION
**Pull request by ezequielc**
@rodrigopavezi Please review. Cheers

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@ezequielc looks good, the only think missing is to bump the version of the package.json and bower.json  :+1: cheers

**Comment by ezequielc** [comment]
Thanks @rodrigopavezi I forgot about that. Done.

**Comment by ezequielc** [comment]
@alex-deaconu  @rodrigopavezi I changed the text. Please review. Thanks

**Comment by alex-deaconu** [comment]
:+1:

**Pull request merged**
