### PR TITLE
Revert changes to Calendar font translations

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. I need to revert some changes, deploy a PR, and then re-apply these for a subsequent PR. Thx.

**Comment by donnapep** [comment]
@stulees Can you please make this priority? It's holding me up. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
Thanks much.

**Pull request merged**
