### PR TITLE
Revising english URL Field component error translations

### PR DESCRIPTION
**Pull request by stulees**
- Updating to have an error for "url" and for "fileType"

### CODE REVIEW

**Comment by stulees** [comment]
@fjvallarino @donnapep I'm not sure if this PR has been done correctly. I've updated both the `.po` file and `.json` files that I wanted changes made to. Was this necessary to do both? I noticed the gulp task `json-to-po` did not do anything when I just made the change in the `.json` file, is this expected? 

Also, this change is for URL Field which resides in the widget-settings-ui-components repo. Do we need to now ensure that repo points to the latest tagged version? Thanks

**Comment by fjvallarino** [comment]
@stulees The changes only need to be done on the po files. The json files were left as a reference, but they should actually be removed to avoid confusion. The process should be:

- Edit PO files
- Run gulp build

**Comment by stulees** [comment]
@fjvallarino Okay, I removed the changes I'd done to the specific `.json` file. Just the `.po` and generated  full `.json` are now in this PR.

**Comment by donnapep** [comment]
@stulees For error messages everywhere else, we're doing something like "Please choose a spreadsheet." or "Please provide the URL to a valid image." Can we follow that same approach for these? Thx.

**Comment by stulees** [comment]
@donnapep Made some improvements. Please review again, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
