### PR TITLE
Use po files as source for translations

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @donnapep @alex-deaconu please review

### CODE REVIEW

**Comment by donnapep** [comment]
@fjvallarino Ah, OK. This is just the gulpfile changes then. So the .po files themselves will come in a subsequent PR I assume? Thx.

**Comment by fjvallarino** [comment]
@donnapep I can push them now. I just wanted to check if the location where I was planning on placing them is ok and if the whole idea made sense. But yes, it's probably easier with the po files at hand (you can also generate them by running "gulp json-to-po")

**Comment by donnapep** [comment]
@fjvallarino I guess we'd need @alanclayton to jump in at this point, as he had mentioned wanting just one po file and this will generate multiple. Thx.

**Comment by alanclayton** [comment]
@donnapep can you clarify for me on the multiple PO files? What would each PO file be used for? Locale? App?

**Comment by fjvallarino** [comment]
@alanclayton Each locale will have a set of files. Inside each locale, based on what is already in the JSON files, I think we would be splitting the translations based on module/application.

**Comment by donnapep** [comment]
@alanclayton If you go [here](http://goo.gl/fdzDrP) you will see all the .po files that get generated for English, for example. If you click on one you can see the text that's in it.

**Comment by alanclayton** [comment]
@donnapep @fjvallarino I'm okay with that. Having everything in one location will be helpful. If a User submits a PO file for a specific Widget can one of you confirm what the process would look like for adding that translation? Thanks

**Comment by donnapep** [comment]
@alanclayton Are you sure you're OK with having that many po files? It means that whenever a user wants to translate something they'll have to open up each one and translate the text in it instead of just opening one file that contains all translations.

I'll let Francisco speak to the process for adding a translation.

**Comment by fjvallarino** [comment]
@donnapep @alanclayton I'm not sure how the contributions were done previously. One way is having users fork the repository and then asking a pull request (overkill if users are not technical), or, as you said on the meeting, having them send the files via email and we merge them somehow (it's a bit more work for us, in that case).

Regarding having a single file, I don't think it's a good idea. We would have all the components and applications translation messages in a single place, which will make for a huge file eventually. If the user wants to translate a single component, it's easier to find it if we keep the translations in separate files. Besides, if we have a single file, we will have to add a prefix to each translation message (
e.g., "storage-client.file.name" instead of "file.name" inside storage-client.po).

**Comment by alanclayton** [comment]
@donnapep I don't think there is a perfect solution. As @fjvallarino mentions, having one PO file per app will make it easier for the end user and reduce the risk in things breaking globally. 

@fjvallarino in re: to the process. let's assume the User will always give the PO file to us. What will I need to do in order to get that translation added to the respective app?

**Comment by fjvallarino** [comment]
@alanclayton In that case, I don't think it would be different to what you did previously. You would have to get the latest version from the repository, compare/merge the files (the one sent by the user against the latest in the repository), commit to a new branch and request a PR.

**Comment by donnapep** [comment]
@alanclayton I'm OK with the current structure, just want you to be aware that not every app will map to a single po file. For example, Weather Widget has some of its translations in weather.po, but it also has shared translations in common.po and widgets.po. Thx.

**Comment by alanclayton** [comment]
@donnapep understood

**Comment by tejohnso** [comment]
@donnapep / @alex-deaconu Were you able to test this with one of the affected components and confirm we are okay to merge?

**Comment by donnapep** [comment]
@tejohnso I have not, but we need to start versioning this repo as I had a situation recently where I had to roll back a Widget, and after the rollback occurred the translations broke. So I think we should version this repo with this change since it's significant and then we can start using the tagged version.

**Comment by alex-deaconu** [comment]
@tejohnso as per the conversation on the trello card, the .json files are not changing so I'm not sure what exactly we need to test/verify. Thanks.

**Comment by fjvallarino** [comment]
I tested Storage and it looks ok. The test would be a sort of confirmation
that the conversion process went smoothly, nothing else.

**Comment by tejohnso** [comment]
Okay @fjvallarino go ahead and merge this and add a tag to the previous version as well as this newly merged version.  If anybody has difficulties they can use the previous version while any problems are sorted out.

**Pull request merged**
