### PR TITLE
Fixed presentation text

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu fixing a small issue. please review. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi the colon there is necessary (http://screencast.com/t/JTqTyB9xs6) or are you adding it in the markup instead? Thanks!

**Comment by rodrigopavezi** [comment]
@alex-deaconu I know, I am adding it to the markup so the presentation word can be reused. cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi sounds good. Thanks for the clarification! :+1:

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome!!

**Pull request merged**
