### PR TITLE
Add common translations needed by Image Widget

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees I added Scale to Fit and Alignment to the widgets property. Please review. Thx.

**Comment by stulees** [comment]
@donnapep Do you think the Position Setting component should use the Alignment property as its label instead? :+1:

**Comment by donnapep** [comment]
@stulees Yeah, probably. Not sure what's in the background mockup but in Image Widget specs it's labelled as Alignment.

**Comment by donnapep** [comment]
@stulees Actually, maybe that Alignment label should move into the file for components?

**Comment by stulees** [comment]
@donnapep Yeah sounds good, will do, thanks

**Pull request merged**
