### PR TITLE
update windows version

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@ezequielc @alex-deaconu please review

### CODE REVIEW

**Comment by ezequielc** [comment]
@ghislaineguerin Looks good. You need to update version in `bower.json` and `package.json`. Cheers

**Comment by ghislaineguerin** [comment]
@ezequielc you mean on rise-vision-apps

**Comment by ezequielc** [comment]
@ghislaineguerin No, in this repo. We update the version numbers before tagging/releasing it.

https://github.com/Rise-Vision/common-i18n/blob/master/bower.json#L3
https://github.com/Rise-Vision/common-i18n/blob/master/package.json#L3

Cheers

**Comment by ghislaineguerin** [comment]
@ezequielc how should it look like?

**Comment by ezequielc** [comment]
@ghislaineguerin You can run `gulp bump` and it will update automatically. Or you can set them manually to `1.3.47`. Cheers

**Comment by ghislaineguerin** [comment]
@ezequielc done. please review.

**Comment by ezequielc** [comment]
@ghislaineguerin Awesome! Looks good :+1: Thanks!

**Pull request merged**
