### PR TITLE
Update Player Warning message

### PR DESCRIPTION
**Pull request by RV-Adrian**
@alex-deaconu @ezequielc 
New message content for 'Simplify Display Setup' card
Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@RV-Adrian looks good :+1: .

However, since this is a versioned repo, you need to increment the version number. Can you please run `gulp bump` in your local environment and commit? Also, once merged we need to create a new release for the repo (1.3.26). Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Thanks! Created tag 1.3.26
Okay to merge?

**Comment by alex-deaconu** [comment]
@RV-Adrian looks good. Thanks for updating!

**Comment by RV-Adrian** [comment]
@alex-deaconu No prob! Thanks for the info on the process :+1:

**Pull request merged**
