### PR TITLE
Add Image Folder Widget translations

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@fjvallarino @stulees I added a gulp `bump` task and updated the version numbers in `bower.json` and `package.json. I think we want to be bumping the version with every PR, correct? Please review. Thx.

**Comment by donnapep** [comment]
@fjvallarino @stulees Can someone review please? Thx.

**Comment by stulees** [comment]
@donnapep Was going to let @fjvallarino speak to the addition of a `bump`, but I'm good with it. :+1:

**Comment by donnapep** [comment]
@stulees I figured as much. Thx.

**Pull request merged**
