### PR TITLE
Adding Order translations and revising video

### PR DESCRIPTION
**Pull request by stulees**
- Adding english translations for Order
- Removing unused translations for Video
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees There are already order translations in `image-folder.json`. If you need them too, then we should move them into `widgets.json`.

**Comment by stulees** [comment]
@donnapep I took these translations from `image-folder.json`. I've created an `orders.json` because I've made a new component `order-setting` in widget-settings-ui-components so that it (select field) can be reused between our widgets. I'll be initiating a PR for it once this one is merged. Thanks

**Comment by donnapep** [comment]
@stulees OK, let's decide on a naming convention right now then since it's getting hard to find stuff in this repo. Some of our widget translations start with `widget-`, others do not. My preference for Widgets would be to start naming them after the repo, so prefixing the translation file name with `widget-`. That way they'll all be ordered alphabetically and easier to find the one you want.

For components, I think they should adopt the component name. So `order.json` would be `order-setting.json`.

And while we're on that subject, some components in `widget-settings-ui-components` have `-setting` at the end; others do not. Shouldn't they either all have `-setting` or none have `-setting`? I vote none since every component in there is a setting and it just makes the names that much longer. Thoughts?

**Comment by stulees** [comment]
@donnapep I agree on prefixing widget translations with `widget-`. When I'm ready with video folder translation, I'll follow that naming convention.

Unfortunately, `widget-settings-ui-components` has the majority of its components with an affix `-setting` and this repo does not follow that (no affix). I actually like the affix `-setting` because I think it would provide a better indication in this repo of what the translation is for. 

Either way, in whichever repo we do all this name changing, it will affect all our widgets. Do you want to change them all or do you want to leave as is and start now with a definitive naming convention?

**Comment by donnapep** [comment]
@stulees We have started using versioning, so some Widgets won't even be affected by this. The others wouldn't be affected unless we were to rebuild, and if we were to rebuild we could just change Bower to use an older version. So, I think we should start following the naming conventions now and then just update other Widgets to follow those conventions when we touch them next.

**Comment by stulees** [comment]
@donnapep In reviewing everything again, right now I'm good with changing all the widget related translation files to ensure a prefix of `widget-`. When a widget needs rebuilding, it will need to be updated to reflect this change.

I would like to hold off making any name changes to the components in `widget-settings-ui-components` as this has a much larger affect. I can make a card and put in our backlog to address this as soon as Video Folder Widget is delivered. I feel more comfortable doing this all at once without a Widget also in process of development. Okay?

**Comment by donnapep** [comment]
@stulees To clarify, I wasn't suggesting that you do any of this now, and in fact I don't think that you should. I just wanted us to establish a naming convention that you would be able to use starting with this PR.

Also, if we do this in a single pass, we're going to be hitting QA with a lot of Widgets to test in a very short period of time. Perhaps we should just leave `widget-settings-ui-components` as is but start following this naming convention moving forward?

**Comment by stulees** [comment]
@donnapep Okay sounds good. To also comment on your question about why `widget-settings-ui-components` have some named with `-setting` and some don't, it was initially to differentiate closely related components. Eg. `column-selector` and `column-setting`. I think moving forward `-setting` is not required in the name and shouldn't be used if not needing to differentiate to a closely related component. So given that, I won't name the component `order-setting` in `widget-settings-ui-components`, I will name it `order`, in which case the translation file in this PR can remain as it is and nothing needs changing. Let me know, thanks.

**Comment by stulees** [comment]
@donnapep FYI, I did have to now change the version bump to be in sync with a release Tyler just did. Have done so and rebased.

**Comment by donnapep** [comment]
@stulees "I love it when a plan comes together."
Although I do wish other people would remember to bump the version. :+1:

**Comment by stulees** [comment]
@donnapep Haha, I'm hearing the theme song in my head right now

**Pull request merged**
