### PR TITLE
Update Raspbian entry to Beta

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc 
Alan requested a 'beta' label for the Pi Player. Updated the i18n entries here, and then will use this as a release in https://github.com/Rise-Vision/rise-vision-apps/pull/387
Thx!

**Comment by ezequielc** [comment]
@RV-Adrian Wouldn't it be better to have the Beta at the beginning or end of the label? Or maybe an icon in the button? Thanks

**Comment by alex-deaconu** [comment]
@RV-Adrian also, don't forget to bump bower.json/package.json versions. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc I was working off https://www.screencast.com/t/IVBGiYzlVBPU , but now that you point it out.. prepending with [BETA] may be a worthy change. I'll mention on the card.

@alex-deaconu Will do! Thanks

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc Version bumped, and placed [BETA] at start of Raspbian label. Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian 👍  Thanks!

**Pull request merged**
