### PR TITLE
Unsaved changes modal

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu I will open the PR so you can review it, but after playing for a while I think I might need to change the behavior of the Save button from the Unsaved changes modal. 

After saving, I am cancelling the state change because we auto create the first Schedule and show a modal to the user, so it makes sense to stay in the Editor, as it is implemented.
But now, after rebasing, I realized it doesn't play nice with the Change Template button, because if the user saves, he will stay in the Editor instead of seeing the Templates modal.
@RV-Adrian I will need you input on this as well. Thanks!

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ezequielc Not too clear on the user impact here. Let's chat at standup!

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu 
Thinking about it some more, I am still leaning to have 'Change Template' NOT ask to Save their work.
The reasons again:
- If the users hits 'Change Template', they are in the mindset to explore and not work with Displays.
- If they do lose some work, this could have a side benefit of showing users how important 'Save' is in the process as @alex-deaconu mentioned. That's not obvious from that start.

While there is no ideal solution that won't require a new card, I do think this is the best option and we can observe results. I think the scenario of a user who puts in a lot of work before exploring Templates and how to Save, is less likely than a user that jumps straight into a Template and is ready to 'Add A Display' in 3 mins.  UX triage?

**Comment by alex-deaconu** [comment]
@ezequielc this PR looks good 👍 . Thanks.

**Comment by ezequielc** [comment]
@RV-Adrian I don't really like the idea of users losing work, specially as it is their first experience with Rise. But as you said, any other solution would require extra work and we really want to close the epic.
My suggestion is implemented as you suggested for now and add a card to Miranda Buffer to review this behavior after the Design Sprint. Thoughts? Thanks

**Pull request merged**
