### PR TITLE
URL Field video error message

### PR DESCRIPTION
**Pull request by stulees**
- Updating the file types allowed

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I thought ogg was audio and ogv was video?

**Comment by stulees** [comment]
@donnapep In theory yes but they have the same MIME type of `ogg`. I have read that technically either can be used (also `.oga` for audio) but it's encouraged to use `.ogv` for video. It's a bit confusing so I'm basically going to allow for either `.ogg` or `.ogv` to pass.

**Comment by donnapep** [comment]
@stulees OK, although in the past when we supported video I believe it was only .ogv. You might want to run this by Support. :+1:

**Pull request merged**
